name: Build and Test Golang Program
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-versions: 1.20

      - name: Print Secrete
        env: 
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        

      - name: Build and test the Program
        run: |
          go build main.go
          ./main